(function(){
  'use strict';
  const PATH='bpt/agenda_v2',LOCAL='bpt_agenda_v2_cache';
  let events=[],selectedId='',cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),bound=false;
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
  const identity=()=>String(window.bptAgendaGetIdentity?.()||localStorage.getItem('bpt_live3_identity_name')||'').trim()||'Invité';
  const players=()=>[...new Set((window.bptAgendaGetPlayers?.()||[]).filter(p=>p?.active!==false&&p?.name).map(p=>String(p.name).trim()))].sort((a,b)=>a.localeCompare(b,'fr'));
  const ref=()=>window.bptFirebaseDb?.()?.ref?.(PATH)||null;
  const dateKey=d=>{const x=d instanceof Date?d:new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
  const today=dateKey(new Date());
  const label=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}):'Date à définir';
  const normalize=v=>Object.entries(v||{}).map(([id,e])=>({...e,id})).filter(e=>e.date);
  function cache(){try{localStorage.setItem(LOCAL,JSON.stringify(events))}catch(_){} }
  function readCache(){try{return JSON.parse(localStorage.getItem(LOCAL)||'[]')}catch(_){return[]}}
  function currentResponses(e){const r=e.responses||{},all=players().concat(Object.keys(r));return [...new Set(all)].reduce((o,n)=>{(o[r[n]||'pending']||(o[r[n]||'pending']=[])).push(n);return o},{present:[],absent:[],maybe:[],pending:[]})}
  function counts(e){const r=currentResponses(e);return `✓ ${r.present.length} · ? ${r.maybe.length} · ✕ ${r.absent.length} · — ${r.pending.length}`}
  async function load(){
    try{const dbx=ref();events=dbx?normalize((await dbx.once('value')).val()):readCache();if(dbx)dbx.off('value').on('value',snap=>{events=normalize(snap.val());cache();render();openNearest()});}
    catch(_){events=readCache()}
    cache();render();openNearest();
    const e=events.find(x=>x.date===today);window.bptAgendaGetTodayEvent=()=>e||null;window.dispatchEvent(new CustomEvent('bpt-agenda-ready',{detail:{event:e||null}}));
  }
  async function save(e){events=events.filter(x=>x.id!==e.id).concat(e).sort((a,b)=>String(a.date+a.time).localeCompare(String(b.date+b.time)));cache();const dbx=ref();if(dbx)await dbx.child(e.id).set(e);render();openNearest()}
  async function remove(e){events=events.filter(x=>x.id!==e.id);cache();const dbx=ref();if(dbx)await dbx.child(e.id).remove();selectedId='';render()}
  function responseColumns(e){const r=currentResponses(e),names=[['present','Présents'],['maybe','Peut-être'],['absent','Absents'],['pending','Sans réponse']];return `<div class="bpt-agenda-v2-responses">${names.map(([k,t])=>`<div><h3>${t} · ${r[k].length}</h3><ul>${r[k].map(n=>`<li>${esc(n)}</li>`).join('')||'<li class="muted">Personne</li>'}</ul></div>`).join('')}</div>`}
  function choices(e,target){const value=(e.responses||{})[target]||'';return `<div class="bpt-agenda-v2-choice">${[['present','✓ Présent'],['absent','✕ Absent'],['maybe','? Peut-être']].map(([k,t])=>`<button type="button" data-agenda-choice="${k}" class="${value===k?'is-active':''}">${t}</button>`).join('')}</div>`}
  function openNearest(){const modal=$('bptAgendaPopupV2');if(!modal)return;const now=dateKey(new Date()),end=new Date();end.setDate(end.getDate()+14);const max=dateKey(end),e=events.filter(x=>x.date>=now&&x.date<=max).sort((a,b)=>String(a.date+a.time).localeCompare(String(b.date+b.time)))[0];if(!e){modal.hidden=true;return}const name=identity();modal.dataset.eventId=e.id;$('bptAgendaPopupContent').innerHTML=`<h2>${esc(label(e.date))}</h2><p class="muted">🕘 ${esc(e.time||'21:00')} · 📍 ${esc(e.location||'Lieu à définir')}</p><p>Votre réponse :</p>${choices(e,name)}${responseColumns(e)}`;modal.hidden=false}
  function renderCalendar(){const host=$('bptAgendaDaysV2');if(!host)return;const y=cursor.getFullYear(),m=cursor.getMonth();$('bptAgendaMonth').textContent=new Date(y,m,1).toLocaleDateString('fr-FR',{month:'long',year:'numeric'});host.replaceChildren();const first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++){const b=document.createElement('button');b.className='bpt-agenda-v2-day';b.disabled=true;b.style.visibility='hidden';host.append(b)}for(let d=1;d<=last;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,e=events.find(x=>x.date===iso),b=document.createElement('button');b.type='button';b.className='bpt-agenda-v2-day'+(e?' is-event':'')+(e&&iso<today?' is-past':'')+(e?.id===selectedId?' is-selected':'');b.textContent=d;b.onclick=()=>{if(e){selectedId=e.id;renderDetail()}else openForm(iso)};host.append(b)}}
  function renderList(){const host=$('bptAgendaListV2');if(!host)return;const upcoming=events.filter(e=>e.date>=today).slice(0,12);host.innerHTML=upcoming.length?upcoming.map(e=>`<button type="button" class="bpt-agenda-v2-event" data-agenda-event="${esc(e.id)}"><strong>${esc(label(e.date))}</strong><small>🕘 ${esc(e.time||'21:00')} · 📍 ${esc(e.location||'Lieu à définir')}</small><span class="bpt-agenda-v2-counts">${esc(counts(e))}</span></button>`).join(''):'<p class="muted">Aucune partie programmée.</p>';host.querySelectorAll('[data-agenda-event]').forEach(b=>b.onclick=()=>{selectedId=b.dataset.agendaEvent;renderDetail()})}
  function renderDetail(){const box=$('bptAgendaDetailV2');if(!box)return;const e=events.find(x=>x.id===selectedId);if(!e){box.hidden=true;return}box.hidden=false;box.innerHTML=`<h2>${esc(label(e.date))}</h2><p class="muted">🕘 ${esc(e.time||'21:00')} · 📍 ${esc(e.location||'Lieu à définir')}</p>${responseColumns(e)}<div class="bpt-btnrow"><button class="btn ghost" id="bptAgendaEditV2" type="button">Modifier</button><button class="btn ghost" id="bptAgendaDeleteV2" type="button">Supprimer</button>${e.gameNumber?'<button class="btn primary" id="bptAgendaOpenGameV2" type="button">Voir la partie</button>':''}</div>`;$('bptAgendaEditV2').onclick=()=>openForm(e.date,e);$('bptAgendaDeleteV2').onclick=()=>remove(e);$('bptAgendaOpenGameV2')?.addEventListener('click',()=>window.bptOpenLatestGame?.(e.gameNumber))}
  function openForm(date='',existing=null){const box=$('bptAgendaDetailV2');if(!box)return;box.hidden=false;const me=identity(),venueNames=players(),current=existing?.location||`Chez ${me}`;box.innerHTML=`<h2>${existing?'Modifier la partie':'Nouvelle partie'}</h2><div class="bpt-agenda-v2-form"><label>Date<input id="bptAgendaDateV2" type="date" value="${esc(existing?.date||date)}"></label><label>Heure<input id="bptAgendaTimeV2" type="time" value="${esc(existing?.time||'21:00')}"></label><label>Lieu<select id="bptAgendaLocationV2">${venueNames.map(n=>`<option value="${esc(n)}" ${current===`Chez ${n}`||current===n?'selected':''}>Chez ${esc(n)}</option>`).join('')}</select></label></div><div class="bpt-btnrow"><button class="btn primary" id="bptAgendaSaveV2" type="button">Enregistrer</button><button class="btn ghost" id="bptAgendaCancelV2" type="button">Annuler</button></div>`;$('bptAgendaSaveV2').onclick=async()=>{const d=$('bptAgendaDateV2').value;if(!d)return;const e={...(existing||{}),id:existing?.id||`agenda_${Date.now()}`,date:d,time:$('bptAgendaTimeV2').value||'21:00',location:`Chez ${$('bptAgendaLocationV2').value}`,createdBy:existing?.createdBy||me,responses:existing?.responses||{[me]:'present'}};selectedId=e.id;await save(e)};$('bptAgendaCancelV2').onclick=()=>{selectedId='';render()}}
  function bind(){if(bound)return;bound=true;$('bptAgendaPrev')?.addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()-1);renderCalendar()});$('bptAgendaNext')?.addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()+1);renderCalendar()});$('bptAgendaNew')?.addEventListener('click',()=>openForm(today));$('bptAgendaPopupClose')?.addEventListener('click',()=>{$('bptAgendaPopupV2').hidden=true});$('bptAgendaPopupValidate')?.addEventListener('click',async()=>{$('bptAgendaPopupV2').hidden=true});$('bptAgendaPopupV2')?.addEventListener('click',async ev=>{const btn=ev.target.closest('[data-agenda-choice]');if(!btn)return;const e=events.find(x=>x.id===$('bptAgendaPopupV2').dataset.eventId);if(!e)return;e.responses=e.responses||{};e.responses[identity()]=btn.dataset.agendaChoice;await save(e);openNearest()});document.addEventListener('click',ev=>{const b=ev.target.closest('[data-view="agenda"],[data-mobile-nav-view="agenda"]');if(b)setTimeout(()=>{render();openNearest()},0)});load()}
  window.BPTAgenda={load,save,openForm};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind,{once:true}):bind();
  function render(){renderCalendar();renderList();renderDetail()}
})();
